### ISSUE TITLE
Design scalable deployment architecture

### ISSUE THREAD

**Issue by miraculixx** [miraculixx/otp-dockerdeploy#4]
### Expected behaviour
1. achieve t < 2 seconds response time (not including network latency) of a `/plan` query with loads of up to 100 concurrent clients 
2. Attempt sub or near linear scalability with a factor <= 1 (i.e. adding 2x clients results in at most 2x the necessary infrastructure)

### Tasks
1. Assess ways to achieve this goal -- is it possible *at all*? at what cost (CPU & memory requirements, #otp instances etc.)
2. Design appropriate deployment architecture (in general, using docker for easy deployment, but if that fails, propose alternative approach). 
3. Make an estimate to create the respective docker image(s) and scripts for deployment. This shall have the ability to add/remove instances at run time (e.g. `otpdeploy scale +5` to add 5 instances) 

### Implementation notes
* probably required to use  a front-end server for load balancing, please use nginx 
* the whole thing must be command-line deployable, as a start you may assume ssh-capable machines to be available. A subsequent story should allow for server creating on the fly too.

### Some references on performance
* https://groups.google.com/forum/#!topic/opentripplanner-users/oB-OwC4_RdM
* https://github.com/opentripplanner/OpenTripPlanner/wiki/JVMPerformance

**Comment by pablokbs** [comment]
Ok. I've trying with shipyard. It looks good. The scale thingy works fine and we should test it on production. Still we are going to need a server in front of these backend servers to balance the load between them. 

Where can I install it ?

**Comment by miraculixx** [comment]
Please see Skype message. 

>Still we are going to need a server in front of these backend servers to balance the load between them.

sure -- I prefer nginx as a front-end server as we use that in other installations already. We need this automated, so that basically we can install from the command line with a new server. Not sure what is the fastest/simplest to do this.

**Comment by pablokbs** [comment]
Tell me what you think about https://github.com/miraculixx/otp-dockerdeploy/commit/282aada7f767f3baf2b26fa967c9eb565aed7822
