### ISSUE TITLE
build.sh and run.sh should accepts 1-n URLs, and additional options for otp.jar

### ISSUE THREAD

**Issue by miraculixx** [miraculixx/otp-dockerdeploy#5]
Expected:
1. accept `--url url1,url2,url3` => wget all of them 
2. accept '--otp "--whatever value"` where everything in the quotes is passed verbatim to the otp.jar call.

Alternative:
If parameters like does not work, can we use env variables instead? E.g. OTP_URLS=url1,url2 and OTP_PARAM="--whatever value" ...

Why?
Rationale for 1: load as many feeds and osm maps as we need
Rationale for 2: enable scenarios for building the graph without osm data, e.g. 

```
a) to build: java -Xmx8G -jar /var/otp/otp.jar --build /var/otp/pdx --noStreets --longDistance
b) for the server: java -Xmx6G -Xverify:none -jar /var/otp/otp.jar --noStreets --longDistance --graphs /var/otp/graphs -s -p 80 
```

Example:
`docker run otpimage --url http://feed1,http://feed2 --otp "--noStreets --longDistance"`

or 

`docker run otpimage -e OTP_URLS=http://feed1,http://feed2 -e OTP_PARAMS="--noStreets --longDistance"`

**Comment by miraculixx** [comment]
@pablokbs just realized this is not done yet. Are you working on this? We need to be able to run the loader with multiple only 1 and multiple URLs (I think that is done, but if I give it only 1 it fails). Also we need to be able to pass the otp parameters to be able to build without PDX.

**Comment by pablokbs** [comment]
Partial work done https://github.com/miraculixx/otp-dockerdeploy/commit/c61c866cd88a8bccc8715426722e8d5a80e4c084

Now you can pass N parameters to the build script, still no OPT parameters.

**Comment by pablokbs** [comment]
Finished.

Please check this cf55185

**Comment by miraculixx** [comment]
:+1:  this looks good.  however, it appears the version on dockerhub is not at the current version -- please update.

```
# docker run --volumes-from server pablokbs/opentripplanner:builder -u "http://14420919.ngrok.com/sample-gtfs.zip" -e "-noStreets --longDistance"
wget: invalid option -- 'u'
Usage: wget [OPTION]... [URL]...

Try `wget --help' for more options.
```

**Comment by pablokbs** [comment]
I've already pushed it and it's working. [There was a small typo on the doc] (https://github.com/miraculixx/otp-dockerdeploy/commit/1ebc8390b20e635b73b0f85ee1ad8f534325df1b), in your example your parameter is using only one dash and it needs two, that's it. 

I've tried running the same command with that url and it failed, I used another url and it worked. Are you sure that this url is correct? Please check.
